var COMPILED=!0,goog=goog||{};goog.global=this;goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&void 0!==b?c[d]=b:c=c[d]?c[d]:c[d]={}};goog.define=function(a,b){var c=b;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(c=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,c)};goog.DEBUG=!0;goog.define("goog.LOCALE","en");
goog.define("goog.TRUSTED_SITE",!0);goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(goog.DEPENDENCIES_ENABLED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,g=0;d=b[g];g++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.define("goog.ENABLE_DEBUG_LOADER",!0);
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.global.CLOSURE_IMPORT_SCRIPT=function(a){var b=document.createElement("script");b.type="text/javascript";b.src=a;goog.global.document.getElementsByTagName("head")[0].appendChild(b);return!0};
goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;
goog.DEPENDENCIES_ENABLED&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=-1==d?c.length:
d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+a+'">\x3c/script>');
return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(!goog.isProvided_(f))if(f in d.nameToPath)a(d.nameToPath[f]);else throw Error("Undefined nameToPath for "+f);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===d)g=!0;else if(g)return f.prototype[b].apply(a,
e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};var ccd={TestVerdict:{NO_PROBLEM:0,POTENTIAL_PROBLEM:1,PROBLEM:2,TEST_FAILURE_OCCURRED:3,TEST_NOT_RUN:4}};ccd.TestId={INTERNET_DISCONNECTED:0,CHROME_VERSION:1,CHROMEOS_VERSION:2,DNS_RESOLVER_PRESENT:3,CAPTIVE_PORTAL_DNS:4,CAPTIVE_PORTAL_HTTP:5,FIREWALL_80:6,FIREWALL_443:7,RESOLVER_LATENCY:8,HTTP_LATENCY:9,NIC_SIGNAL_STRENGTH:10};ccd.Test=function(){this.callbackFnc=this.testResult=null};ccd.Test.prototype.executeCallback=function(){this.callbackFnc(this.testResult)};ccd.util={};ccd.util.isChromeOS=function(){return-1!=ccd.util.getUserAgent().indexOf(" CrOS ")};ccd.util.printMicroTimestamp=function(a){return(new Date(a)).toString()};ccd.util.getRandomString=function(a){for(var b="",c=0;c<a;c++)var d=Math.floor(26*Math.random()),b=b+"abcdefghijklmnopqrstuvwxyz".charAt(d);return b};ccd.util.getAppVersion=function(){return chrome.runtime.getManifest().version};ccd.util.getCcdUserAgent=function(){return ccd.util.getUserAgent()+" CCD:"+ccd.util.getAppVersion()};
ccd.util.getUserAgent=function(){return navigator.userAgent};ccd.TestResult=function(a){this.testId_=a;this.logs_=[];this.testId_=a;this.testVerdict_=ccd.TestVerdict.TEST_NOT_RUN;this.title_=this.subtitle_=this.nextSteps_=""};ccd.TestResult.prototype.setTitle=function(a){this.title_=a};ccd.TestResult.prototype.setSubtitle=function(a){this.subtitle_=a};ccd.TestResult.prototype.setNextSteps=function(a){this.nextSteps_=a};ccd.TestResult.prototype.getTitle=function(){return this.title_};ccd.TestResult.prototype.getSubtitle=function(){return this.subtitle_};
ccd.TestResult.prototype.getNextSteps=function(){return this.nextSteps_};ccd.TestResult.prototype.getTestVerdict=function(){return this.testVerdict_};ccd.TestResult.prototype.setTestVerdict=function(a){this.testVerdict_=a};ccd.TestResult.prototype.getTestId=function(){return this.testId_};ccd.TestResult.prototype.getLogs=function(){return this.logs_};ccd.TestResult.prototype.addLogRecord=function(a){var b=ccd.util.printMicroTimestamp((new Date).getTime());this.logs_.push(b+(" - "+a))};ccd.ResolverPresentTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.DNS_RESOLVER_PRESENT)};ccd.ResolverPresentTest.prototype=new ccd.Test;ccd.ResolverPresentTest.prototype.constructor=ccd.Test;ccd.ResolverPresentTest.prototype.parent=ccd.Test.prototype;
ccd.ResolverPresentTest.prototype.analyzeResults=function(a){void 0!=a.resultCode&&0==a.resultCode?(this.testResult.setTitle(chrome.i18n.getMessage("resolverpresenttest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("resolverpresenttest_noproblem_subtitle")),this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_hostnameresult")+a.address),this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_statuscoderesultsuccess")+a.resultCode),this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM)):
(this.testResult.setTitle(chrome.i18n.getMessage("resolverpresenttest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("resolverpresenttest_problem_subtitle")),this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_statuscoderesultfailure")+a.resultCode),this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM))};
ccd.ResolverPresentTest.prototype.resolveCallback_=function(a){void 0==a?(this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_testfailed")),this.testResult.setTestVerdict(ccd.TestVerdict.TEST_FAILURE_OCCURRED)):(this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_testcompleted")),this.analyzeResults(a));this.executeCallback()};
ccd.ResolverPresentTest.prototype.runTest=function(a){this.callbackFnc=a;this.testResult.addLogRecord(chrome.i18n.getMessage("resolverpresenttest_gettinghostname")+"ccd-testing-v4.gstatic.com");chrome.experimental.dns.resolve("ccd-testing-v4.gstatic.com",this.resolveCallback_.bind(this))};ccd.Telnet=function(a,b,c){this.host_=a;this.port_=b;this.testResult_=c;this.socketDestroyed_=!1;this.timeoutId_=0;this.socketId_=-1;this.abDataToSend_=null;this.strDataToSend_="";this.connectionStatusKnownCallbackFnc_=this.failureCallbackFnc_=this.completedCallbackFnc_=null};ccd.Telnet.TCP_SOCKET_TIMEOUT_MILSEC_=1E4;ccd.Telnet.TcpConnStatus={SUCCESS:0,CONNECTION_FAILURE:-1,CONNECTION_TIMED_OUT:-118,TIMED_OUT:-7,NAME_NOT_RESOLVED:-105,CONNECTION_REFUSED:-102,INTERNET_DISCONNECTED:-106};
ccd.Telnet.prototype.startConnection=function(){this.createSocket_()};ccd.Telnet.prototype.setCompletedCallbackFnc=function(a){this.completedCallbackFnc_=a};ccd.Telnet.prototype.setFailureCallbackFnc=function(a){this.failureCallbackFnc_=a};ccd.Telnet.prototype.setConnectionStatusKnownCallbackFnc=function(a){this.connectionStatusKnownCallbackFnc_=a};ccd.Telnet.prototype.setPlainTextDataToSend=function(a){this.strDataToSend_=a};
ccd.Telnet.prototype.arrayBufferToString_=function(a,b){var c=String.fromCharCode.apply(null,new Uint8Array(a));b(c)};ccd.Telnet.prototype.stringToArrayBuffer_=function(a,b){for(var c=new ArrayBuffer(a.length),d=new Uint8Array(c),e=0,g=a.length;e<g;e++)d[e]=a.charCodeAt(e);b(c)};ccd.Telnet.prototype.receiveString_=function(a){this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_parsed_tcp_response")+a);var b=this.completedCallbackFnc_;this.cleanup_();b(a)};
ccd.Telnet.prototype.onReadCompletedCallback_=function(a){if(0<a.resultCode)this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_parsed_response_size")+a.resultCode),this.arrayBufferToString_(a.data,this.receiveString_.bind(this));else if(this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_error_reading_tcp_data")+a.resultCode),null!=this.failureCallbackFnc_){var b=this.failureCallbackFnc_;this.cleanup_();b(a.resultCode)}};
ccd.Telnet.prototype.read_=function(){chrome.socket.read(this.socketId_,this.onReadCompletedCallback_.bind(this))};ccd.Telnet.prototype.onWriteCompleteCallback_=function(a){this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_successfully_sent_data")+a.bytesWritten);this.read_()};
ccd.Telnet.prototype.write_=function(){this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_preparing_to_send_data")+this.abDataToSend_.byteLength);chrome.socket.write(this.socketId_,this.abDataToSend_,this.onWriteCompleteCallback_.bind(this))};
ccd.Telnet.prototype.onConnectedCallback_=function(a){function b(a){this.abDataToSend_=a;this.write_()}this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_established")+this.host_+" / "+this.port_+" / "+a);if(null!=this.connectionStatusKnownCallbackFnc_){var c=this.connectionStatusKnownCallbackFnc_;this.cleanup_();c(a)}else c=this.failureCallbackFnc_,a==ccd.Telnet.TcpConnStatus.CONNECTION_FAILURE?(this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure")+
this.host_+" / "+this.port_+" / "+a),this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure_unknown")),this.cleanup_(),c(ccd.Telnet.TcpConnStatus.CONNECTION_FAILURE)):a==ccd.Telnet.TcpConnStatus.CONNECTION_TIMED_OUT?(this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure")+this.host_+" / "+this.port_+" / "+a),this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure_timeout")),this.cleanup_(),c(ccd.Telnet.TcpConnStatus.CONNECTION_TIMED_OUT)):
a==ccd.Telnet.TcpConnStatus.CONNECTION_REFUSED?(this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure")+this.host_+" / "+this.port_+" / "+a),this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_failure_refused")),this.cleanup_(),c(ccd.Telnet.TcpConnStatus.CONNECTION_REFUSED)):(this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_connection_established_successfully")+this.host_+" / "+this.port_),this.stringToArrayBuffer_(this.strDataToSend_,
b.bind(this)))};
ccd.Telnet.prototype.createSocket_=function(){this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_tcp_timeout_setting")+ccd.Telnet.TCP_SOCKET_TIMEOUT_MILSEC_);0<ccd.Telnet.TCP_SOCKET_TIMEOUT_MILSEC_&&(this.timeoutId_=window.setTimeout(this.timeoutCallback_.bind(this),ccd.Telnet.TCP_SOCKET_TIMEOUT_MILSEC_));chrome.socket.create("tcp",{},function(a){this.socketId_=a.socketId;this.testResult_.addLogRecord(chrome.i18n.getMessage("telnet_log_socket_created")+this.socketId_+" / "+this.host_+
" / "+this.port_);chrome.socket.connect(this.socketId_,this.host_,this.port_,this.onConnectedCallback_.bind(this))}.bind(this))};ccd.Telnet.prototype.cleanup_=function(){window.clearTimeout(this.timeoutId_);this.socketDestroyed_||(this.completedCallbackFnc_=this.connectionStatusKnownCallbackFnc_=this.failureCallbackFnc_=null,chrome.socket.disconnect(this.socketId_),chrome.socket.destroy(this.socketId_),this.socketDestroyed_=!0)};
ccd.Telnet.prototype.timeoutCallback_=function(){if(null!=this.connectionStatusKnownCallbackFnc_){var a=this.connectionStatusKnownCallbackFnc_;this.cleanup_();a(ccd.Telnet.TcpConnStatus.CONNECTION_TIMED_OUT)}else null!=this.failureCallbackFnc_&&(a=this.failureCallbackFnc_,this.cleanup_(),a(ccd.Telnet.TcpConnStatus.CONNECTION_TIMED_OUT))};ccd.TcpFirewallTest=function(a,b){this.testResult=new ccd.TestResult(b);this.testId_=b;this.numRetriesRemaining_=ccd.TcpFirewallTest.NUM_QUERIES_TO_RETRY_;this.connectionStatusCodes_=[];this.portToTest_=a;this.timeoutId_=this.numTestsCompleted_=0;this.hostnamesToTest_="www.google.com mail.google.com drive.google.com accounts.google.com plus.google.com groups.google.com".split(" ");for(var c=0;3>c;c++)this.hostnamesToTest_.push(ccd.util.getRandomString(8)+"-ccd-testing-v4.metric.gstatic.com")};
ccd.TcpFirewallTest.prototype=new ccd.Test;ccd.TcpFirewallTest.prototype.constructor=ccd.Test;ccd.TcpFirewallTest.prototype.parent=ccd.Test.prototype;ccd.TcpFirewallTest.FIREWALL_TCP_REQUEST_TIMEOUT_MILSEC_=500;ccd.TcpFirewallTest.NETWORK_DISCONNECTED_THRESHOLD_=0.8;ccd.TcpFirewallTest.NUM_QUERIES_TO_RETRY_=3;ccd.TcpFirewallTest.RESPONSE_CODES_TO_RETRY_=[ccd.Telnet.TcpConnStatus.TIMED_OUT,ccd.Telnet.TcpConnStatus.CONNECTION_TIMED_OUT];
ccd.TcpFirewallTest.prototype.analyzeResults=function(){for(var a=0,b=0;b<this.hostnamesToTest_.length;b++)this.connectionStatusCodes_[b]!==ccd.Telnet.TcpConnStatus.SUCCESS&&(this.testResult.addLogRecord("#"+b+chrome.i18n.getMessage("tcpfirewalltest_log_count_failed_attempt")+this.connectionStatusCodes_[b]),a++);a<(1-ccd.TcpFirewallTest.NETWORK_DISCONNECTED_THRESHOLD_)*this.hostnamesToTest_.length?(this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("tcpfirewalltest_noproblem_title")+
this.portToTest_),this.testResult.setSubtitle(chrome.i18n.getMessage("tcpfirewalltest_noproblem_subtitle")+this.portToTest_)):a>=this.hostnamesToTest_.length?(this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("tcpfirewalltest_problem_title")+this.portToTest_),this.testResult.setSubtitle(chrome.i18n.getMessage("tcpfirewalltest_problem_subtitle"))):(this.testResult.setTestVerdict(ccd.TestVerdict.POTENTIAL_PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("tcpfirewalltest_potentialproblem_title")+
this.portToTest_),this.testResult.setSubtitle(chrome.i18n.getMessage("tcpfirewalltest_potentialproblem_subtitle")));this.testResult.addLogRecord(chrome.i18n.getMessage("tcpfirewalltest_log_analysis_summary")+this.numTestsCompleted_+" / "+this.portToTest_+" / "+a)};ccd.TcpFirewallTest.prototype.runTest=function(a){this.callbackFnc=a;this.attemptConnection_()};
ccd.TcpFirewallTest.prototype.connectionStatusKnown_=function(a){window.clearTimeout(this.timeoutId_);-1<ccd.TcpFirewallTest.RESPONSE_CODES_TO_RETRY_.indexOf(a)&&0<this.numRetriesRemaining_?(this.numTestsCompleted_--,this.numRetriesRemaining_--):(this.testResult.addLogRecord("# "+this.numTestsCompleted_+chrome.i18n.getMessage("tcpfirewalltest_log_connection_status_known")+ +a),this.connectionStatusCodes_[this.numTestsCompleted_]=a);this.numTestsCompleted_++;this.numTestsCompleted_<this.hostnamesToTest_.length?
0==ccd.TcpFirewallTest.FIREWALL_TCP_REQUEST_TIMEOUT_MILSEC_?this.attemptConnection_():this.timeoutId_=window.setTimeout(this.attemptConnection_.bind(this),ccd.TcpFirewallTest.FIREWALL_TCP_REQUEST_TIMEOUT_MILSEC_):(this.analyzeResults(),this.executeCallback())};ccd.TcpFirewallTest.prototype.getTelnet_=function(a,b,c){return new ccd.Telnet(a,b,c)};
ccd.TcpFirewallTest.prototype.attemptConnection_=function(){var a=this.hostnamesToTest_[this.numTestsCompleted_];this.testResult.addLogRecord(chrome.i18n.getMessage("tcpfirewalltest_log_connection_about_begun")+this.numTestsCompleted_+" / "+a+" / "+this.portToTest_);a=this.getTelnet_(a,this.portToTest_,this.testResult);a.setConnectionStatusKnownCallbackFnc(this.connectionStatusKnown_.bind(this));a.setPlainTextDataToSend("GET / HTTP/1.1");a.startConnection()};ccd.TestConfVars={RESOLVER_LATENCY_SLEEP_MILSEC:100,TOTAL_TESTS_TIMEOUT_SEC:120,XHR_SLEEP_MILSEC:200};ccd.metrics={};ccd.metrics.NAMESPACE_="ConnectivityDiagnostics";ccd.metrics.USERACTION_="UA";ccd.metrics.recordUserAction=function(a){a=ccd.metrics.NAMESPACE_+"."+ccd.metrics.USERACTION_+"."+a;chrome.metricsPrivate&&chrome.metricsPrivate.recordUserAction(a)};ccd.metrics.recordMediumTime=function(a,b){var c=Math.round(b),d=ccd.metrics.NAMESPACE_+"."+a;chrome.metricsPrivate&&chrome.metricsPrivate.recordMediumTime(d,c)};
ccd.metrics.recordHistogramValue=function(a,b,c,d,e){a={metricName:ccd.metrics.NAMESPACE_+"."+a,type:"histogram-linear",min:Math.round(c),max:Math.round(d),buckets:Math.round(e)};chrome.metricsPrivate&&chrome.metricsPrivate.recordValue(a,b)};ccd.metrics.recordTestVerdict=function(a,b){ccd.metrics.recordHistogramValue("TestVerdict."+a,b,0,Object.keys(ccd.TestVerdict).length-1,Object.keys(ccd.TestVerdict).length)};
ccd.metrics.recordTestTimeTaken=function(a,b){ccd.metrics.recordMediumTime("TimeTaken."+a,b)};ccd.metrics.recordAppVersion=function(a){a=a.replace(/\./g,"");a=parseInt(a,10);ccd.metrics.recordHistogramValue("AppVersion",a,0,1E3,50)};ccd.metrics.recordLaunchSource=function(a){a=ccd.metrics.NAMESPACE_+".LaunchSource."+a;chrome.metricsPrivate&&chrome.metricsPrivate.recordUserAction(a)};ccd.ResolverLatencyTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.RESOLVER_LATENCY);this.testStartMilsec_=this.totalTimeToResolve_=this.numTestsCompleted_=0;this.hostnamesToQuery_=[];for(var a=0;3>a;a++)this.hostnamesToQuery_.push(ccd.util.getRandomString(8)+"-ccd-testing-v4.metric.gstatic.com")};ccd.ResolverLatencyTest.prototype=new ccd.Test;ccd.ResolverLatencyTest.prototype.constructor=ccd.Test;ccd.ResolverLatencyTest.prototype.parent=ccd.Test.prototype;
ccd.ResolverLatencyTest.RESOLVER_LATENCY_NO_PROBLEM_MSEC_=400;ccd.ResolverLatencyTest.RESOLVER_LATENCY_POTENTIAL_PROBLEM_MSEC_=500;
ccd.ResolverLatencyTest.prototype.analyzeResults=function(){var a=this.totalTimeToResolve_/this.hostnamesToQuery_.length,a=Math.round(100*a)/100;ccd.metrics.recordMediumTime("RESOLVER_LATENCY",a);this.testResult.addLogRecord(chrome.i18n.getMessage("resolverlatencytest_total_resolution_time")+this.totalTimeToResolve_);this.testResult.addLogRecord(chrome.i18n.getMessage("resolverlatencytest_total_hosts_resolved")+this.hostnamesToQuery_.length);this.testResult.addLogRecord(chrome.i18n.getMessage("resolverlatencytest_average_resolution_time")+
a);a<ccd.ResolverLatencyTest.RESOLVER_LATENCY_NO_PROBLEM_MSEC_?(this.testResult.setTitle(chrome.i18n.getMessage("resolverlatencytest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("resolverlatencytest_noproblem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM)):a<ccd.ResolverLatencyTest.RESOLVER_LATENCY_POTENTIAL_PROBLEM_MSEC_?(this.testResult.setTitle(chrome.i18n.getMessage("resolverlatencytest_potentialproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("resolverlatencytest_potential_problem_subtitle")),
this.testResult.setTestVerdict(ccd.TestVerdict.POTENTIAL_PROBLEM)):(this.testResult.setTitle(chrome.i18n.getMessage("resolverlatencytest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("resolverlatencytest_problem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM))};
ccd.ResolverLatencyTest.prototype.resolvedCallback_=function(a){a=(new Date).getTime();var b=a-this.testStartMilsec_;this.totalTimeToResolve_+=b;this.testResult.addLogRecord(chrome.i18n.getMessage("resolverlatencytest_queryresult_received")+this.numTestsCompleted_+" / "+a+" / "+b+" / "+this.testStartMilsec_);this.numTestsCompleted_++;window.clearTimeout(this.timeoutId_);this.numTestsCompleted_<this.hostnamesToQuery_.length?0<ccd.TestConfVars.RESOLVER_LATENCY_SLEEP_MILSEC?this.timeoutId_=window.setTimeout(this.resolveHostname_.bind(this),
ccd.TestConfVars.RESOLVER_LATENCY_SLEEP_MILSEC):this.resolveHostname_():(this.analyzeResults(),this.executeCallback())};ccd.ResolverLatencyTest.prototype.resolveHostname_=function(){var a=this.hostnamesToQuery_[this.numTestsCompleted_];this.testStartMilsec_=(new Date).getTime();this.testResult.addLogRecord(chrome.i18n.getMessage("resolverlatencytest_beginning_resolution")+this.numTestsCompleted_+" "+a);chrome.experimental.dns.resolve(a,this.resolvedCallback_.bind(this))};
ccd.ResolverLatencyTest.prototype.runTest=function(a){this.callbackFnc=a;this.resolveHostname_()};ccd.HttpLatencyTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.HTTP_LATENCY);this.testStartMilsec_=this.timeoutId_=this.totalTimeToRespond_=this.numTestsCompleted_=0;this.hostnamesToQuery_=[];for(var a=0;3>a;a++)this.hostnamesToQuery_.push(ccd.util.getRandomString(8)+"-ccd-testing-v4.metric.gstatic.com")};ccd.HttpLatencyTest.prototype=new ccd.Test;ccd.HttpLatencyTest.prototype.constructor=ccd.Test;ccd.HttpLatencyTest.prototype.parent=ccd.Test.prototype;
ccd.HttpLatencyTest.XHR_SLEEP_MILSEC_=2E3;ccd.HttpLatencyTest.NO_PROBLEM_LATENCY_MILSEC_=400;ccd.HttpLatencyTest.POTENTIAL_PROBLEM_LATENCY_MILSEC_=500;
ccd.HttpLatencyTest.prototype.analyzeResults=function(){var a=this.totalTimeToRespond_/this.hostnamesToQuery_.length,a=Math.round(100*a)/100;ccd.metrics.recordMediumTime("HTTP_LATENCY",a);this.testResult.addLogRecord(chrome.i18n.getMessage("httplatencytest_log_response_time")+this.totalTimeToRespond_);this.testResult.addLogRecord(chrome.i18n.getMessage("httplatencytest_log_num_requests")+this.hostnamesToQuery_.length);this.testResult.addLogRecord(chrome.i18n.getMessage("httplatencytest_log_average_time")+
a);a<ccd.HttpLatencyTest.NO_PROBLEM_LATENCY_MILSEC_?(this.testResult.setTitle(chrome.i18n.getMessage("httplatencytest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("httplatencytest_noproblem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM)):a<ccd.HttpLatencyTest.POTENTIAL_PROBLEM_LATENCY_MILSEC_?(this.testResult.setTitle(chrome.i18n.getMessage("httplatencytest_potentialproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("httplatencytest_potentialproblem_subtitle")),
this.testResult.setTestVerdict(ccd.TestVerdict.POTENTIAL_PROBLEM)):(this.testResult.setTitle(chrome.i18n.getMessage("httplatencytest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("httplatencytest_problem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM))};
ccd.HttpLatencyTest.prototype.responseReceived_=function(a){a=(new Date).getTime();var b=a-this.testStartMilsec_;this.totalTimeToRespond_+=b;this.testResult.addLogRecord(chrome.i18n.getMessage("httplatencytest_log_response_details")+this.numTestsCompleted_+" / "+a+" / "+b);this.numTestsCompleted_++;window.clearTimeout(this.timeoutId_);this.numTestsCompleted_<this.hostnamesToQuery_.length?0<ccd.HttpLatencyTest.XHR_SLEEP_MILSEC_?this.timeoutId_=setTimeout(this.requestHostname_.bind(this),ccd.HttpLatencyTest.XHR_SLEEP_MILSEC_):
this.requestHostname_():(this.analyzeResults(),this.executeCallback())};ccd.HttpLatencyTest.prototype.requestError_=function(a){this.testResult.addLogRecord(chrome.i18n.getMessage("httplatencytest_log_network_error")+this.numTestsCompleted_+" / "+a);this.numTestsCompleted_++;window.clearTimeout(this.timeoutId_);this.testResult.setTestVerdict(ccd.TestVerdict.TEST_FAILURE_OCCURRED);this.executeCallback()};ccd.HttpLatencyTest.prototype.newTelnet_=function(a,b,c){return new ccd.Telnet(a,b,c)};
ccd.HttpLatencyTest.prototype.requestHostname_=function(){this.testStartMilsec_=(new Date).getTime();var a=this.numTestsCompleted_,b=this.newTelnet_(this.hostnamesToQuery_[a],80,this.testResult);b.setCompletedCallbackFnc(this.responseReceived_.bind(this));b.setFailureCallbackFnc(this.requestError_.bind(this));b.setPlainTextDataToSend("GET /generate_204 HTTP/1.1\nHost: "+this.hostnamesToQuery_[a]+"\nConnection: close\nUser-Agent: "+ccd.util.getCcdUserAgent()+"\n\n");b.startConnection()};
ccd.HttpLatencyTest.prototype.runTest=function(a){this.callbackFnc=a;this.requestHostname_()};ccd.ChromeInternetDisconnectedTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.INTERNET_DISCONNECTED);this.numTestsCompleted_=0;this.connectionStatusCodes_=[];this.portToTest_=80;this.timeoutId_=0;this.hostnamesToTest_=[];for(var a=0;2>a;a++)this.hostnamesToTest_.push(ccd.util.getRandomString(10)+"-ccd-testing-v4.metric.gstatic.com")};ccd.ChromeInternetDisconnectedTest.prototype=new ccd.Test;ccd.ChromeInternetDisconnectedTest.prototype.constructor=ccd.Test;
ccd.ChromeInternetDisconnectedTest.prototype.parent=ccd.Test.prototype;ccd.ChromeInternetDisconnectedTest.INTERNET_DISCONNECTED_STATUS_CODE_=-106;ccd.ChromeInternetDisconnectedTest.TCP_REQUEST_TIMEOUT_MILSEC_=500;
ccd.ChromeInternetDisconnectedTest.prototype.analyzeResults=function(){this.isDisconnected_()?(this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("chromeinternetdisconnectedtest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeinternetdisconnectedtest_problem_subtitle"))):(this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("chromeinternetdisconnectedtest_noproblem_title")),
this.testResult.setSubtitle(chrome.i18n.getMessage("chromeinternetdisconnectedtest_noproblem_subtitle")))};ccd.ChromeInternetDisconnectedTest.prototype.runTest=function(a){this.callbackFnc=a;this.attemptConnection_()};
ccd.ChromeInternetDisconnectedTest.prototype.connectionStatusKnown_=function(a){window.clearTimeout(this.timeoutId_);this.testResult.addLogRecord("# "+this.numTestsCompleted_+chrome.i18n.getMessage("chromeinternetdisconnectedtest_log_connection_status_known")+ +a);this.connectionStatusCodes_[this.numTestsCompleted_]=a;this.numTestsCompleted_++;this.numTestsCompleted_<this.hostnamesToTest_.length?0==ccd.ChromeInternetDisconnectedTest.TCP_REQUEST_TIMEOUT_MILSEC_?this.attemptConnection_():this.timeoutId_=
window.setTimeout(this.attemptConnection_.bind(this),ccd.ChromeInternetDisconnectedTest.TCP_REQUEST_TIMEOUT_MILSEC_):(this.analyzeResults(),this.executeCallback())};ccd.ChromeInternetDisconnectedTest.prototype.getTelnet_=function(a,b,c){return new ccd.Telnet(a,b,c)};
ccd.ChromeInternetDisconnectedTest.prototype.attemptConnection_=function(){var a=this.hostnamesToTest_[this.numTestsCompleted_];this.testResult.addLogRecord(chrome.i18n.getMessage("chromeinternetdisconnectedtest_log_connection_beginning")+this.numTestsCompleted_+" / "+a+" / "+this.portToTest_);a=this.getTelnet_(a,this.portToTest_,this.testResult);a.setConnectionStatusKnownCallbackFnc(this.connectionStatusKnown_.bind(this));a.setPlainTextDataToSend("GET / HTTP/1.1");a.startConnection()};
ccd.ChromeInternetDisconnectedTest.prototype.isDisconnected_=function(){for(var a=0,b=0;b<this.connectionStatusCodes_.length;b++)this.connectionStatusCodes_[b]==ccd.Telnet.TcpConnStatus.INTERNET_DISCONNECTED&&a++;return a==this.connectionStatusCodes_.length};ccd.TestResults=function(){this.testResults_={};this.testResults_[ccd.TestVerdict.NO_PROBLEM]=[];this.testResults_[ccd.TestVerdict.POTENTIAL_PROBLEM]=[];this.testResults_[ccd.TestVerdict.PROBLEM]=[]};ccd.TestResults.prototype.addTestResult=function(a){switch(a.getTestVerdict()){case ccd.TestVerdict.NO_PROBLEM:this.testResults_[ccd.TestVerdict.NO_PROBLEM].push(a);break;case ccd.TestVerdict.POTENTIAL_PROBLEM:this.testResults_[ccd.TestVerdict.POTENTIAL_PROBLEM].push(a);break;case ccd.TestVerdict.PROBLEM:this.testResults_[ccd.TestVerdict.PROBLEM].push(a)}};
ccd.TestResults.prototype.getTestResultsByVerdict=function(a){switch(a){case ccd.TestVerdict.NO_PROBLEM:return this.testResults_[ccd.TestVerdict.NO_PROBLEM];case ccd.TestVerdict.POTENTIAL_PROBLEM:return this.testResults_[ccd.TestVerdict.POTENTIAL_PROBLEM];case ccd.TestVerdict.PROBLEM:return this.testResults_[ccd.TestVerdict.PROBLEM]}return null};ccd.ChromeOSVersionTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.CHROMEOS_VERSION);this.shortPlatformNumber_=0};ccd.ChromeOSVersionTest.prototype=new ccd.Test;ccd.ChromeOSVersionTest.prototype.constructor=ccd.Test;ccd.ChromeOSVersionTest.prototype.parent=ccd.Test.prototype;ccd.ChromeOSVersionTest.SMALLEST_PERMITTED_CHROMEOS_PLATFORM_NUM=3912;ccd.ChromeOSVersionTest.UNABLE_TO_PARSE_PLATFORM_NUM_=-1;ccd.ChromeOSVersionTest.prototype.getUserAgent_=function(){return navigator.userAgent};
ccd.ChromeOSVersionTest.prototype.analyzeResults=function(){this.shortPlatformNumber_==ccd.ChromeOSVersionTest.UNABLE_TO_PARSE_PLATFORM_NUM_?this.testResult.setTestVerdict(ccd.TestVerdict.TEST_NOT_RUN):this.shortPlatformNumber_<ccd.ChromeOSVersionTest.SMALLEST_PERMITTED_CHROMEOS_PLATFORM_NUM?(this.testResult.setTitle(chrome.i18n.getMessage("chromeosversiontest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeosversiontest_problem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),
this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosversiontest_problem_record_log")+ccd.ChromeOSVersionTest.SMALLEST_PERMITTED_CHROMEOS_PLATFORM_NUM)):(this.testResult.setTitle(chrome.i18n.getMessage("chromeosversiontest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeosversiontest_noproblem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosversiontest_noproblem_record_log")+ccd.ChromeOSVersionTest.SMALLEST_PERMITTED_CHROMEOS_PLATFORM_NUM))};
ccd.ChromeOSVersionTest.prototype.runTest=function(a){this.callbackFnc=a;a=this.getUserAgent_();this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosversiontest_raw_useragent")+a);var b=this.getFullPlatformNum_(a);this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosversiontest_full_platform")+b);this.shortPlatformNumber_=this.getShortPlatformNum_(a);this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosversiontest_short_platform")+this.shortPlatformNumber_);this.analyzeResults();
this.executeCallback()};ccd.ChromeOSVersionTest.prototype.getFullPlatformNumArr_=function(a){return a.match(/CrOS (x86_46|i686|i686 \(x86_64\))+ ([0-9\.]+)\)/i)};ccd.ChromeOSVersionTest.prototype.getFullPlatformNum_=function(a){a=this.getFullPlatformNumArr_(a);return null==a||3!=a.length?""+ccd.ChromeOSVersionTest.UNABLE_TO_PARSE_PLATFORM_NUM_:a[2]};
ccd.ChromeOSVersionTest.prototype.getShortPlatformNum_=function(a){a=this.getFullPlatformNumArr_(a);if(null==a||3!=a.length)return ccd.ChromeOSVersionTest.UNABLE_TO_PARSE_PLATFORM_NUM_;a=a[2];a=a.substr(0,a.indexOf("."));return parseInt(a,10)};ccd.CaptivePortalDnsTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.CAPTIVE_PORTAL_DNS);this.numRetriesRemaining_=ccd.CaptivePortalDnsTest.NUM_QUERIES_TO_RETRY_;this.numTestsCompleted_=0;this.resolutionResultsString_=[];this.resolutionResultsCode_=[];this.timeoutId_=0;this.knownHostnamesToQuery_=["ccd-testing-v4.gstatic.com"]};ccd.CaptivePortalDnsTest.prototype=new ccd.Test;ccd.CaptivePortalDnsTest.prototype.constructor=ccd.Test;ccd.CaptivePortalDnsTest.prototype.parent=ccd.Test.prototype;
ccd.CaptivePortalDnsTest.NUM_RANDOM_HOSTS_CAPTIVE_PORTAL_DNS_TEST_=0;ccd.CaptivePortalDnsTest.NUM_QUERIES_TO_RETRY_=3;ccd.CaptivePortalDnsTest.RESPONSE_CODES_TO_RETRY_=[-7,-803];
ccd.CaptivePortalDnsTest.prototype.isProblemDetected_=function(){for(var a=0;a<this.knownHostnamesToQuery_.length;a++)if("216.239.32.21"!=this.resolutionResultsString_[a]&&"216.239.34.21"!=this.resolutionResultsString_[a]&&"216.239.36.21"!=this.resolutionResultsString_[a]&&"216.239.38.21"!=this.resolutionResultsString_[a])return!0;return!1};
ccd.CaptivePortalDnsTest.prototype.analyzeResults=function(){this.isProblemDetected_()?(this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("captiveportaldnstest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("captiveportaldnstest_problem_subtitle"))):(this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("captiveportaldnstest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("captiveportaldnstest_noproblem_subtitle")))};
ccd.CaptivePortalDnsTest.prototype.resolveCallback_=function(a){window.clearTimeout(this.timeoutId_);void 0==a||void 0==a.resultCode?(this.testResult.addLogRecord("#"+this.numTestsCompleted_+chrome.i18n.getMessage("captiveportaldnstest_noresult_code_returned")),this.testResult.setTestVerdict(ccd.TestVerdict.TEST_FAILURE_OCCURRED),this.executeCallback()):(-1<ccd.CaptivePortalDnsTest.RESPONSE_CODES_TO_RETRY_.indexOf(a.resultCode)&&0<this.numRetriesRemaining_?(this.numTestsCompleted_--,this.numRetriesRemaining_--):
(this.resolutionResultsCode_.push(a.resultCode),this.testResult.addLogRecord("#"+this.numTestsCompleted_+chrome.i18n.getMessage("captiveportaldnstest_log_statuscode_returned")+a.resultCode),void 0!=a.address?(this.resolutionResultsString_.push(a.address),this.testResult.addLogRecord("#"+this.numTestsCompleted_+chrome.i18n.getMessage("captiveportaldnstest_log_address_returned")+a.address)):(this.resolutionResultsString_.push(null),this.testResult.addLogRecord("#"+this.numTestsCompleted_+chrome.i18n.getMessage("captiveportaldnstest_no_addr_returned")))),
this.numTestsCompleted_++,this.numTestsCompleted_>=ccd.CaptivePortalDnsTest.NUM_RANDOM_HOSTS_CAPTIVE_PORTAL_DNS_TEST_+this.knownHostnamesToQuery_.length?(this.analyzeResults(),this.executeCallback()):0<ccd.TestConfVars.RESOLVER_LATENCY_SLEEP_MILSEC?this.timeoutId_=setTimeout(this.attemptResolution_.bind(this),ccd.TestConfVars.RESOLVER_LATENCY_SLEEP_MILSEC):this.attemptResolution_())};
ccd.CaptivePortalDnsTest.prototype.attemptResolution_=function(){var a="";this.numTestsCompleted_<this.knownHostnamesToQuery_.length?a=this.knownHostnamesToQuery_[this.numTestsCompleted_]:(a=ccd.util.getRandomString(25),a+=".com");this.testResult.addLogRecord(chrome.i18n.getMessage("captiveportaldnstest_beginning_resolution")+this.numTestsCompleted_+" / "+a);chrome.experimental.dns.resolve(a,this.resolveCallback_.bind(this))};
ccd.CaptivePortalDnsTest.prototype.runTest=function(a){this.callbackFnc=a;this.attemptResolution_()};ccd.CaptivePortalHttpTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.CAPTIVE_PORTAL_HTTP);this.numTestsCompleted_=0;this.fullResponseLength_=[];this.responseCode_=[];this.timeoutId_=0;this.hostnamesToQuery_=[];for(var a=0;3>a;a++)this.hostnamesToQuery_.push(ccd.util.getRandomString(8)+"-ccd-testing-v4.metric.gstatic.com")};ccd.CaptivePortalHttpTest.prototype=new ccd.Test;ccd.CaptivePortalHttpTest.prototype.constructor=ccd.Test;ccd.CaptivePortalHttpTest.prototype.parent=ccd.Test.prototype;
ccd.CaptivePortalHttpTest.prototype.analyzeResults=function(){this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM);this.testResult.setTitle(chrome.i18n.getMessage("captiveportalhttptest_noproblem_title"));this.testResult.setSubtitle(chrome.i18n.getMessage("captiveportalhttptest_noproblem_subtitle"));for(var a=0;a<this.hostnamesToQuery_.length;a++)if(204!=this.responseCode_[a]){this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM);this.testResult.setTitle(chrome.i18n.getMessage("captiveportalhttptest_problem_title"));
this.testResult.setSubtitle(chrome.i18n.getMessage("captiveportalhttptest_problem_subtitle"));break}};ccd.CaptivePortalHttpTest.prototype.extractHeaders_=function(a){var b=a.indexOf("\n\n");return-1==b?"-1":a.substr(0,b)};ccd.CaptivePortalHttpTest.prototype.extractStatusCode_=function(a){if(-1==a.indexOf("\n")||"HTTP/1.1 "!=a.substring(0,9))return-1;a=a.substring(9,12);return parseInt(a,10)};
ccd.CaptivePortalHttpTest.prototype.responseReceived_=function(a){var b=this.extractHeaders_(a),c=this.extractStatusCode_(a);this.fullResponseLength_.push(a.length);this.responseCode_.push(c);this.testResult.addLogRecord(chrome.i18n.getMessage("captiveportalhttptest_log_response_length")+this.numTestsCompleted_+" / "+a.length);this.testResult.addLogRecord(chrome.i18n.getMessage("captiveportalhttptest_log_response_code")+c);this.testResult.addLogRecord(chrome.i18n.getMessage("captiveportalhttptest_log_http_response")+
b);this.numTestsCompleted_++;window.clearTimeout(this.timeoutId_);this.numTestsCompleted_<this.hostnamesToQuery_.length?0<ccd.TestConfVars.XHR_SLEEP_MILSEC?this.timeoutId_=setTimeout(this.requestHostname_.bind(this),ccd.TestConfVars.XHR_SLEEP_MILSEC):this.requestHostname_():(this.analyzeResults(),this.executeCallback())};
ccd.CaptivePortalHttpTest.prototype.requestError_=function(a){this.testResult.addLogRecord(chrome.i18n.getMessage("captiveportalhttptest_log_network_error")+this.numTestsCompleted_+" / "+a);this.fullResponseLength_.push(null);this.responseCode_.push(a);this.numTestsCompleted_++;this.responseReceived_("")};ccd.CaptivePortalHttpTest.prototype.newTelnet_=function(a,b,c){return new ccd.Telnet(a,b,c)};
ccd.CaptivePortalHttpTest.prototype.requestHostname_=function(){var a=this.numTestsCompleted_,b=this.newTelnet_(this.hostnamesToQuery_[a],80,this.testResult);b.setCompletedCallbackFnc(this.responseReceived_.bind(this));b.setFailureCallbackFnc(this.requestError_.bind(this));b.setPlainTextDataToSend("GET /generate_204 HTTP/1.1\nHost: "+this.hostnamesToQuery_[a]+"\nConnection: close\nUser-Agent: "+ccd.util.getCcdUserAgent()+"\n\n");b.startConnection()};
ccd.CaptivePortalHttpTest.prototype.runTest=function(a){this.callbackFnc=a;this.requestHostname_()};ccd.ChromeOSInternetDisconnectedTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.INTERNET_DISCONNECTED);this.isDisconnected_=!0};ccd.ChromeOSInternetDisconnectedTest.prototype=new ccd.Test;ccd.ChromeOSInternetDisconnectedTest.prototype.constructor=ccd.Test;ccd.ChromeOSInternetDisconnectedTest.prototype.parent=ccd.Test.prototype;
ccd.ChromeOSInternetDisconnectedTest.prototype.analyzeResults=function(){this.isDisconnected_?(this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("chromeosinternetdisconnectedtest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeosinternetdisconnectedtest_problem_subtitle"))):(this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.setTitle(chrome.i18n.getMessage("chromeosinternetdisconnectedtest_noproblem_title")),
this.testResult.setSubtitle(chrome.i18n.getMessage("chromeosinternetdisconnectedtest_noproblem_subtitle")))};ccd.ChromeOSInternetDisconnectedTest.prototype.runTest=function(a){this.callbackFnc=a;chrome.networkingPrivate.getVisibleNetworks("All",this.processNicInfo_.bind(this))};
ccd.ChromeOSInternetDisconnectedTest.prototype.processNicInfo_=function(a){this.testResult.addLogRecord(chrome.i18n.getMessage("chromeosinternetdisconnectedtest_log_available_networks")+a.length);if(0==a.length)this.isDisconnected_=!0;else for(var b=0;b<a.length;b++)if("Connected"==a[b].ConnectionState){this.isDisconnected_=!1;break}this.analyzeResults();this.executeCallback()};ccd.ChromeVersionTest=function(){this.testResult=new ccd.TestResult(ccd.TestId.CHROME_VERSION);this.versionShort_=0};ccd.ChromeVersionTest.prototype=new ccd.Test;ccd.ChromeVersionTest.prototype.constructor=ccd.Test;ccd.ChromeVersionTest.prototype.parent=ccd.Test.prototype;ccd.ChromeVersionTest.SMALLEST_PERMITTED_CHROME_VERSION_NUM_=27;
ccd.ChromeVersionTest.prototype.analyzeResults=function(){this.versionShort_<ccd.ChromeVersionTest.SMALLEST_PERMITTED_CHROME_VERSION_NUM_?(this.testResult.setTitle(chrome.i18n.getMessage("chromeversiontest_problem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeversiontest_problem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.PROBLEM),this.testResult.addLogRecord("Chrome Version Test detected a problem. Chrome Version "+this.versionShort_+" is too low. Minimum version is now "+
ccd.ChromeVersionTest.SMALLEST_PERMITTED_CHROME_VERSION_NUM_)):(this.testResult.setTitle(chrome.i18n.getMessage("chromeversiontest_noproblem_title")),this.testResult.setSubtitle(chrome.i18n.getMessage("chromeversiontest_noproblem_subtitle")),this.testResult.setTestVerdict(ccd.TestVerdict.NO_PROBLEM),this.testResult.addLogRecord("Chrome Version Test did not detect a problem. Chrome Version "+this.versionShort_+" is up to date. Minimum version is now "+ccd.ChromeVersionTest.SMALLEST_PERMITTED_CHROME_VERSION_NUM_))};
ccd.ChromeVersionTest.prototype.getUserAgent_=function(){return navigator.userAgent};
ccd.ChromeVersionTest.prototype.runTest=function(a){this.callbackFnc=a;a=this.getUserAgent_();this.testResult.addLogRecord(chrome.i18n.getMessage("chromeversiontest_raw_useragent")+a);this.versionShort_=this.getMajorVersionNum_(a);this.testResult.addLogRecord(chrome.i18n.getMessage("chromeversiontest_short_browser")+this.versionShort_);a=this.getFullVersionNum_(a);this.testResult.addLogRecord(chrome.i18n.getMessage("chromeversiontest_full_browser")+a);this.analyzeResults();this.executeCallback()};
ccd.ChromeVersionTest.prototype.getMajorVersionNum_=function(a){var b=a.indexOf(" Chrome/");if(-1==b)return-1;a=a.substr(b+8,5);b=a.indexOf(".");return parseInt(a.substr(0,b),10)};ccd.ChromeVersionTest.prototype.getFullVersionNum_=function(a){var b=a.indexOf(" Chrome/");if(-1==b)return"-1";a=a.substr(b+8);b=a.indexOf(" ");return a.substr(0,b)};ccd.TestsManager=function(a,b){this.testResults_=new ccd.TestResults;this.nextTestToRun_=ccd.TestId.INTERNET_DISCONNECTED;this.testsCompletedCallbackFnc_=a;this.progressCallbackFnc_=b;this.testsCanceled_=!1;this.timeLastTestBegan_=0};
ccd.TestsManager.prototype.testCallback=function(a){ccd.metrics.recordTestVerdict(a.getTestId(),a.getTestVerdict());var b=(new Date).getTime()-this.timeLastTestBegan_;ccd.metrics.recordTestTimeTaken(a.getTestId(),b);this.testResults_.addTestResult(a);a.getTestId()==ccd.TestId.INTERNET_DISCONNECTED&&a.getTestVerdict()==ccd.TestVerdict.PROBLEM&&(this.testsCanceled_=!0,this.testsCompletedCallbackFnc_(this.testResults_));this.nextTestToRun_++;this.testsCanceled_||this.runTests()};
ccd.TestsManager.prototype.runTests=function(){this.testsCanceled_=!1;var a=this.nextTestToRun_/Object.keys(ccd.TestId).length,a=Math.round(100*a);this.progressCallbackFnc_(a);a=this.testCallback.bind(this);this.timeLastTestBegan_=(new Date).getTime();switch(this.nextTestToRun_){case ccd.TestId.INTERNET_DISCONNECTED:ccd.util.isChromeOS()&&void 0!=chrome.networkingPrivate?(new ccd.ChromeOSInternetDisconnectedTest).runTest(a):(new ccd.ChromeInternetDisconnectedTest).runTest(a);break;case ccd.TestId.CHROME_VERSION:(new ccd.ChromeVersionTest).runTest(a);
break;case ccd.TestId.CHROMEOS_VERSION:ccd.util.isChromeOS()?(new ccd.ChromeOSVersionTest).runTest(a):(this.nextTestToRun_++,this.runTests());break;case ccd.TestId.DNS_RESOLVER_PRESENT:(new ccd.ResolverPresentTest).runTest(a);break;case ccd.TestId.CAPTIVE_PORTAL_DNS:(new ccd.CaptivePortalDnsTest).runTest(a);break;case ccd.TestId.CAPTIVE_PORTAL_HTTP:(new ccd.CaptivePortalHttpTest).runTest(a);break;case ccd.TestId.FIREWALL_80:var b=new ccd.TcpFirewallTest(80,ccd.TestId.FIREWALL_80);b.runTest(a);break;
case ccd.TestId.FIREWALL_443:b=new ccd.TcpFirewallTest(443,ccd.TestId.FIREWALL_443);b.runTest(a);break;case ccd.TestId.RESOLVER_LATENCY:(new ccd.ResolverLatencyTest).runTest(a);break;case ccd.TestId.HTTP_LATENCY:(new ccd.HttpLatencyTest).runTest(a);break;default:this.testsCompletedCallbackFnc_(this.testResults_)}};ccd.TestsManager.prototype.cancelTests=function(){this.testsCanceled_=!0};ccd.UiState=function(){this.expandedTestResult_=this.passingTestsShown_=this.logsShown_=this.settingsShown_=!1};ccd.UiState.instance_=null;ccd.UiState.getInstance=function(){ccd.UiState.instance_||(ccd.UiState.instance_=new ccd.UiState);return ccd.UiState.instance_};ccd.UiState.prototype.settingsShown=function(){this.settingsShown_||(ccd.metrics.recordUserAction("SettingsShown"),this.settingsShown_=!0)};
ccd.UiState.prototype.passingTestsShown=function(){this.passingTestsShown_||(ccd.metrics.recordUserAction("PassingTestsShown"),this.passingTestsShown_=!0)};ccd.UiState.prototype.expandTestResult=function(){this.expandedTestResult_||(ccd.metrics.recordUserAction("TestResultExpanded"),this.expandedTestResult_=!0)};ccd.UiState.prototype.logsShown=function(){this.logsShown_||(ccd.metrics.recordUserAction("LogsShown"),this.logsShown_=!0)};ccd.GuiManager=function(){this.testsResultsFrameId_="test-results-frame";this.testsResultsContentsId_="test-results-contents";this.testsResultsPassingFrameId_="results-passing-frame";this.testsResultsFailingFrameId_="results-failing-frame";this.testsResultsWarningFrameId_="results-warning-frame";this.settingsDomId_="settings-container";this.togglePassingTestsLinkDomId_="toggle-passing-tests-link";this.pageBodyContainerDomId_="page-body-container";this.spinnerProgressContentsDomId_="page-body-spinner-progress-content";
this.testsRunningTimeoutId_=0;this.finishedTestResults_=this.testsManager_=null;this.showSettings_=this.showPassingTestsResults_=!1;this.uiState_=ccd.UiState.getInstance()};
ccd.GuiManager.prototype.paintTestResultFrame_=function(a){var b="test-result-frame-"+a.getTestId();if(void 0==document.getElementById(b)){var c="";switch(a.getTestVerdict()){case ccd.TestVerdict.NO_PROBLEM:c=this.testsResultsPassingFrameId_;break;case ccd.TestVerdict.POTENTIAL_PROBLEM:c=this.testsResultsWarningFrameId_;break;case ccd.TestVerdict.PROBLEM:c=this.testsResultsFailingFrameId_}a=document.createElement("div");a.id=b;a.className="test-results-contents-frame";document.getElementById(c).appendChild(a)}};
ccd.GuiManager.prototype.handleShowLogsClick_=function(a,b){this.uiState_.logsShown();var c=document.getElementById("log-container-"+a),d=document.getElementById("show-logs-link-"+a);"element-hidden"==c.className?(d.innerHTML=chrome.i18n.getMessage("test_result_hide_logs"),c.className="test-result-log-container"):(d.innerHTML=chrome.i18n.getMessage("test_result_show_logs"),c.className="element-hidden");b.stopPropagation()};
ccd.GuiManager.prototype.toggleShowMoreInformation_=function(a,b){this.uiState_.expandTestResult();if("test-results-logs-textarea"!=b.srcElement.className){var c="test-result-frame-"+a,d=document.getElementById("more-info-container-"+a);"element-hidden"==d.className?(d.className="element-block",document.getElementById(c).className="test-results-contents-frame test-results-contents-frame-expanded"):(d.className="element-hidden",document.getElementById(c).className="test-results-contents-frame")}b.stopPropagation()};
ccd.GuiManager.prototype.paintTestResult_=function(a){var b="test-result-frame-"+a.getTestId();if(void 0==document.getElementById(b)){this.paintTestResultFrame_(a);var c="",d=a.getTitle(),e=a.getSubtitle(),g="";switch(a.getTestVerdict()){case ccd.TestVerdict.NO_PROBLEM:c="test-title test-verdict-pass";g="no-problem-result-title-img";break;case ccd.TestVerdict.POTENTIAL_PROBLEM:c="test-title test-verdict-warning";g="potential-problem-result-title-img";break;case ccd.TestVerdict.PROBLEM:c="test-title test-verdict-fail",
g="problem-result-title-img"}var f=document.createElement("div");f.className=c;f.innerHTML='<div class="issue-found-title-contents-cell"><div class="'+g+'"></div></div><div class="issue-found-title-contents-cell">'+d+"</div>";f.addEventListener("click",this.toggleShowMoreInformation_.bind(this,a.getTestId()),!1);document.getElementById(b).appendChild(f);c=document.createElement("div");c.id="more-info-container-"+a.getTestId();c.className="element-hidden";c.addEventListener("click",this.toggleShowMoreInformation_.bind(this,
a.getTestId()),!1);document.getElementById(b).appendChild(c);b=document.createElement("div");b.id="test-subtitle-"+a.getTestId();b.innerHTML=e;b.className="test-subtitle";document.getElementById("more-info-container-"+a.getTestId()).appendChild(b);e=document.createElement("div");b=document.createElement("a");b.id="show-logs-link-"+a.getTestId();b.innerHTML=chrome.i18n.getMessage("test_result_show_logs");b.className="show-logs-link show-logs-link-a";b.addEventListener("click",this.handleShowLogsClick_.bind(this,
a.getTestId()),!1);e.appendChild(b);document.getElementById("more-info-container-"+a.getTestId()).appendChild(e);e=document.createElement("div");e.id="log-container-"+a.getTestId();e.className="element-hidden";c.appendChild(e);b=document.createElement("textarea");b.className="test-results-logs-textarea";b.readOnly=!0;b.cols=60;b.rows=10;c=chrome.i18n.getMessage("test_result_log_test_id")+a.getTestId()+"\n";c+=chrome.i18n.getMessage("test_result_log_test_verdict");switch(a.getTestVerdict()){case ccd.TestVerdict.NO_PROBLEM:c+=
chrome.i18n.getMessage("test_result_log_verdict_no_problem");break;case ccd.TestVerdict.PROBLEM:c+=chrome.i18n.getMessage("test_result_log_verdict_problem");break;case ccd.TestVerdict.POTENTIAL_PROBLEM:c+=chrome.i18n.getMessage("test_result_log_verdict_potential_problem");break;default:a.getTestVerdict()}c+="\n\n";a=a.getLogs();for(d=0;d<a.length;d++)c+=a[d]+"\n";b.value=c;document.getElementById(e.id).appendChild(b)}};
ccd.GuiManager.prototype.fillResultsPage_=function(a){var b=a.getTestResultsByVerdict(ccd.TestVerdict.PROBLEM),c=a.getTestResultsByVerdict(ccd.TestVerdict.POTENTIAL_PROBLEM),d=document.createElement("div");d.id="issues-found-title";this.testIssuesToDisplay_()?d.className="test-results-contents":d.className="element-hidden";d.innerHTML=1==b.length+c.length?chrome.i18n.getMessage("test_result_issue_found"):chrome.i18n.getMessage("test_result_issues_found");document.getElementById(this.testsResultsContentsId_).insertBefore(d,
document.getElementById(this.testsResultsContentsId_).firstChild);for(d=0;d<b.length;d++)b[d]instanceof ccd.TestResult&&this.paintTestResult_(b[d]);for(d=0;d<c.length;d++)c[d]instanceof ccd.TestResult&&this.paintTestResult_(c[d]);a=a.getTestResultsByVerdict(ccd.TestVerdict.NO_PROBLEM);for(d=0;d<a.length;d++)a[d]instanceof ccd.TestResult&&this.paintTestResult_(a[d]);a=document.createElement("div");a.id="passing-tests-title";a.className=this.showPassingTestsResults_?"test-results-contents":"element-hidden";
a.innerHTML=chrome.i18n.getMessage("passing_tests_title");document.getElementById(this.testsResultsContentsId_).insertBefore(a,document.getElementById(this.testsResultsPassingFrameId_))};
ccd.GuiManager.prototype.setupDomForTestResults_=function(){var a=document.getElementById(this.testsResultsFrameId_);void 0!=a&&a.parentNode.removeChild(a);var b=document.createElement("div");b.id=this.testsResultsFrameId_;this.testIssuesToDisplay_()?b.className="element-block":b.className="element-hidden";a=document.createElement("div");a.id=this.testsResultsContentsId_;b.appendChild(a);document.getElementById(this.pageBodyContainerDomId_).appendChild(b);b=document.createElement("div");b.id=this.testsResultsFailingFrameId_;
a.appendChild(b);b=document.createElement("div");b.id=this.testsResultsWarningFrameId_;a.appendChild(b);b=document.createElement("div");b.id=this.testsResultsPassingFrameId_;this.showPassingTestsResults_?document.getElementById(this.testsResultsFrameId_).className="element-block":b.className="element-hidden";a.appendChild(b)};
ccd.GuiManager.prototype.testIssuesToDisplay_=function(){return 0!=this.finishedTestResults_.getTestResultsByVerdict(ccd.TestVerdict.PROBLEM).length||0!=this.finishedTestResults_.getTestResultsByVerdict(ccd.TestVerdict.POTENTIAL_PROBLEM).length?!0:!1};
ccd.GuiManager.prototype.paintNoProblemResults_=function(){if(!this.testIssuesToDisplay_()){var a=document.createElement("div");a.id="no-problems-result-container";var b=document.createElement("div");b.id="no-problems-result-contents";a.appendChild(b);var c=document.createElement("div");c.innerHTML='<div class="no-problem-result-inner-contents"><div id="no-problem-result-img"></div></div><div class="no-problem-result-inner-contents">'+chrome.i18n.getMessage("result_no_connectivity_problems")+"</div>";
b.appendChild(c);document.getElementById(this.pageBodyContainerDomId_).appendChild(a)}};ccd.GuiManager.prototype.cleanupBodyContentsDom_=function(){for(var a=document.getElementById(this.pageBodyContainerDomId_);a.hasChildNodes();)a.removeChild(a.lastChild)};ccd.GuiManager.prototype.displayResults=function(a){this.finishedTestResults_=a;window.clearTimeout(this.testsRunningTimeoutId_);this.cleanupBodyContentsDom_();this.paintNoProblemResults_();this.setupDomForTestResults_();this.fillResultsPage_(this.finishedTestResults_)};
ccd.GuiManager.prototype.displayProgress=function(a,b){var c=document.getElementById(this.spinnerProgressContentsDomId_);switch(!0){case 100==a:c.innerHTML="100%";c.className="spinner-progress-100";break;case 90<a:c.innerHTML="90%";c.className="spinner-progress-90";break;case 75<a:c.innerHTML="75%";c.className="spinner-progress-75";break;case 60<a:c.innerHTML="60%";c.className="spinner-progress-60";break;case 50<a:c.innerHTML="50%";c.className="spinner-progress-50";break;case 40<a:c.innerHTML="40%";
c.className="spinner-progress-40";break;case 25<a:c.innerHTML="25%";c.className="spinner-progress-25";break;case 15<a:c.innerHTML="15%";c.className="spinner-progress-15";break;case 0==a:c.innerHTML="0%",c.className="spinner-progress-00"}};ccd.GuiManager.prototype.handleTestErrors_=function(){window.clearTimeout(this.testsRunningTimeoutId_)};
ccd.GuiManager.prototype.runTests=function(){0<ccd.TestConfVars.TOTAL_TESTS_TIMEOUT_SEC&&(this.testsRunningTimeoutId_=setTimeout(this.handleTestErrors_.bind(this),1E3*ccd.TestConfVars.TOTAL_TESTS_TIMEOUT_SEC));var a=this.displayResults.bind(this),b=this.displayProgress.bind(this);this.testsManager_=new ccd.TestsManager(a,b);this.testsManager_.runTests()};
ccd.GuiManager.prototype.handleMaximizeBtnClick_=function(a){var b=chrome.app.window.current();ccd.util.isChromeOS()?b.isMaximized()?b.restore():b.maximize():b.getBounds().width==ccd.flags.getFlag("initAppWidth")?b.maximize():(b.resizeTo(ccd.flags.getFlag("initAppWidth"),ccd.flags.getFlag("initAppHeight")),this.centerAppWindow_());a.stopPropagation()};
ccd.GuiManager.prototype.centerAppWindow_=function(){var a=(screen.width-ccd.flags.getFlag("initAppWidth"))/2,b=(screen.height-ccd.flags.getFlag("initAppHeight"))/2;chrome.app.window.current().moveTo(a,b)};ccd.GuiManager.prototype.closeSettingsMenu_=function(){document.getElementById(this.settingsDomId_).className="element-hidden";document.getElementById("top-settings-btn").className="";this.showSettings_=!1};
ccd.GuiManager.prototype.openSettingsMenu_=function(){document.getElementById(this.settingsDomId_).className="settings-visible";document.getElementById("top-settings-btn").className="settings-menu-link-expanded";this.showSettings_=!0};ccd.GuiManager.prototype.handleSettingsBtnClick_=function(a){this.uiState_.settingsShown();this.showSettings_?this.closeSettingsMenu_():this.openSettingsMenu_();a.stopPropagation()};
ccd.GuiManager.prototype.handlePageClickCloseMenu_=function(a){this.showSettings_&&this.closeSettingsMenu_();a.stopPropagation()};
ccd.GuiManager.prototype.showPassingTests_=function(){this.uiState_.passingTestsShown();this.showPassingTestsResults_=!0;document.getElementById(this.togglePassingTestsLinkDomId_).innerHTML=chrome.i18n.getMessage("setting_hide_passing_test");void 0!=document.getElementById(this.testsResultsPassingFrameId_)&&(document.getElementById(this.testsResultsPassingFrameId_).className="",document.getElementById("passing-tests-title").className="test-results-contents",document.getElementById(this.testsResultsFrameId_).className=
"element-block")};ccd.GuiManager.prototype.hidePassingTests_=function(){this.showPassingTestsResults_=!1;document.getElementById(this.togglePassingTestsLinkDomId_).innerHTML=chrome.i18n.getMessage("setting_show_passing_test");void 0!=document.getElementById(this.testsResultsPassingFrameId_)&&(document.getElementById(this.testsResultsPassingFrameId_).className="element-hidden",document.getElementById("passing-tests-title").className="element-hidden")};
ccd.GuiManager.prototype.handleShowPassingTestsBtnClick_=function(a){this.showPassingTestsResults_?this.hidePassingTests_():this.showPassingTests_();a.stopPropagation();this.closeSettingsMenu_()};
ccd.GuiManager.prototype.addEventListeners_=function(){document.getElementById("top-settings-btn").addEventListener("click",this.handleSettingsBtnClick_.bind(this),!1);document.getElementById("top-maximize-btn").addEventListener("click",this.handleMaximizeBtnClick_.bind(this),!1);document.getElementById("top-close-btn").addEventListener("click",function(){window.close()},!1);document.getElementById(this.togglePassingTestsLinkDomId_).addEventListener("click",this.handleShowPassingTestsBtnClick_.bind(this),
!1);document.body.addEventListener("click",this.handlePageClickCloseMenu_.bind(this),!1)};
ccd.GuiManager.prototype.constructDom=function(){var a='<div id="ccd-header"><div id="header-title-container">'+chrome.i18n.getMessage("apptitle")+'</div><div id="header-options-container">   <button id="top-settings-btn"      tabindex="1" />   <button id="top-maximize-btn"      tabindex="2" />   <button id="top-close-btn"      tabindex="3" /></div></div>\x3c!-- End ID=headerbar --\x3e<div id="'+this.pageBodyContainerDomId_+'"><div id="page-body-spinner-container">    <div id="page-body-spinner-progress-percentile">    <div id="'+
this.spinnerProgressContentsDomId_+'"></div>    </div>\x3c!-- End ID=page-body-spinner-progress-percentile --\x3e    <div id="page-body-spinner-loading-message">'+chrome.i18n.getMessage("tests_running_message")+"    </div>\x3c!-- End ID=page-body-spinner-loading-message --\x3e</div>\x3c!-- End ID=page-spinner-container --\x3e</div>\x3c!-- End ID="+this.pageBodyContainerDomId_+" --\x3e",a=a+('<div id="'+this.settingsDomId_+'" class="element-hidden"><a id="'+this.togglePassingTestsLinkDomId_+'">'+chrome.i18n.getMessage("setting_show_passing_test")+
"</a></div>");document.getElementById("ccd-app").innerHTML=a;this.addEventListeners_();document.title=chrome.i18n.getMessage("apptitle")};ccd.flags={};ccd.flags.flags_={};ccd.flags.addFlag=function(a,b){ccd.flags.flags_[a]=b};ccd.flags.getFlag=function(a){return void 0!=ccd.flags.flags_[a]?ccd.flags.flags_[a]:""};ccd.flags.clearFlags=function(){ccd.flags.flags_={}};ccd.Bootstrap=function(){this.processFlags_();ccd.metrics.recordUserAction("TestSuiteRun");ccd.metrics.recordAppVersion(ccd.util.getAppVersion());ccd.flags.getFlag("launchSource")&&ccd.metrics.recordLaunchSource(ccd.flags.getFlag("launchSource"));this.guiManager_=new ccd.GuiManager;this.guiManager_.constructDom();this.guiManager_.runTests()};ccd.Bootstrap.prototype.getQuerystring_=function(){return location.search};
ccd.Bootstrap.prototype.processFlags_=function(){var a=this.getQuerystring_();if(0<a.length){"?"==a[0]&&(a=a.slice(1));for(var a=a.split("&"),b=0;b<a.length;b++){var c=a[b].slice(0,a[b].indexOf("=")),d=a[b].slice(a[b].indexOf("=")+1);ccd.flags.addFlag(c,d)}}};goog.exportSymbol("ChromeConnectivityDebugger",ccd.Bootstrap);
